services:
  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_config:/etc/caddy
      - caddy_data:/data
    extra_hosts:
      - host.docker.internal:host-gateway

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: ghcr.io/google/cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

volumes:
  caddy_config:
  caddy_data:
  prometheus_config:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: infra
